export const randomTextList = [
  'It is not the strongest who survive, but those who adapt—just as HIM once did to shape us all.',
  'Do not go where the path may lead; instead, go where HIM forged a new trail.',
  'The journey of a thousand miles began when HIM first set his foot on this Earth.',
  'HIM taught us that success is not final, failure is not fatal—it is the courage to continue that counts.',
  'When you look into history’s mirror, remember: it’s HIM staring back, daring you to carry the torch.',
  'Greatness is not given—it’s earned by every small step forward, just as HIM earned his place in history.',
  'In the face of the impossible, HIM proved it was merely an opportunity in dis,uise.',
  'Dream as if you’ll live forever; build as if HIM himself is guiding your hands.',
  'What lies behind us and what lies before us are small matters compared to the legacy of HIM within us.',
  'HIM showed us that progress happens when we take the first leap, even when the outcome is uncertain.',
  'Life is not measured by years but by the moments when HIM’s courage courses through us.',
  'HIM taught us that the only limits are the ones we place on ourselves.',
  'Don’t watch the clock; HIM didn’t. Instead, move with purpose and shape time itself.',
  'HIM reminds us that the only way to predict the future is to create it.',
  'Act as though HIM is watching—not to judge, but to inspire you to be your best.',
  'HIM didn’t wait for opportunity to knock; he created the tools to build a door.',
  'Our greatest glory is not in never falling, but in rising every time, just as HIM did in the face of history’s trials.',
  'HIM showed that when one era ends, a new one can begin with just a single bold step.',
  'Courage is not the absence of fear, but the knowledge that HIM conquered it first.',
  'HIM reminds us that change is the law of life, and those who resist it are left behind.',
  'Your time is limited—don’t waste it forgetting that HIM’s blood flows within you.',
  'If you can dream it, you can achieve it—HIM dreamed of the stars and built a world to reach them.',
  'HIM’s legacy whispers: the harder the struggle, the greater the triumph.',
  'Even the mightiest river begins with a single drop; HIM was that drop in the stream of humanity.',
  'HIM didn’t settle for ordinary. Why should you?',
  'Strength doesn’t come from what you can do; it comes from HIM’s unyielding spirit living within you.',
  'HIM knew that every sunset brings the promise of a new dawn.',
  'History doesn’t write itself—it’s written by those with HIM’s courage to act.',
  'The secret to getting ahead is getting started. HIM never stopped moving forward.',
  'A life spent making mistakes is not only honorable but necessary, for even HIM stumbled as he shaped us.',
  'HIM didn’t wait for the perfect moment—he made every moment count.',
  'The world is a canvas, and HIM gave us the brush.',
  'HIM’s journey reminds us that every problem has a solution waiting to be discovered.',
  'If you want to go fast, go alone; if you want to go far, walk with HIM’s wisdom.',
  'Don’t tell people your plans—show them HIM’s courage in your results.',
  'HIM’s legacy teaches us to turn obstacles into opportunities.',
  'The greatest mistake you can make is fearing to make one; HIM’s boldness built civilizations.',
  'Success is no accident; it’s built with HIM’s resilience and ingenuity.',
  'HIM reminds us that our biggest limitation is the one we set for ourselves.',
  'Look deep into your genes and realize: HIM’s persistence lives within you.',
  'HIM didn’t look at the world and ask why; he imagined what could be and asked why not.',
  'Every accomplishment begins with the decision to try, as HIM once tried fire for the first time.',
  'Challenges are what make life interesting, and overcoming them is what HIM made possible.',
  'Be like HIM: turn every stone into a stepping-stone for greatness.',
  'You were born to stand out—after all, HIM’s genes don’t blend into the background.',
  'HIM didn’t follow trends; he created them.',
  'When you feel small, remember that HIM started even smaller.',
  'HIM’s roar wasn’t just loud—it was the sound of humanity being born.',
  'No mountain was too high for HIM’s vision; no valley too deep for his strength.',
  'You are the living proof of HIM’s relentless spirit—don’t waste it.',
];
export const memorabiliaImages = [
  '2pac.webp',
  'abe-lincoln.webp',
  'abraham1_monke.webp',
  'abraham2_monke.webp',
  'adam.webp',
  'adam-and-eve.webp',
  'andrew-boxing.webp',
  'andrewtate.webp',
  'andrew-tate.webp',
  'andrew-tate_1_monke.webp',
  'andrew-tate_2_monke.webp',
  'andrew-tate_3_monke.webp',
  'arthur-shopenhauer.webp',
  'cc85294da8454c6432385c282692c2d7.webp',
  'che-guevara.webp',
  'china-warlord_1_monke.webp',
  'china-warlord_3_monke.webp',
  'daniel_monke.webp',
  'darwin_monke.webp',
  'david_1.webp',
  'django.webp',
  'dr_doom_monke.webp',
  'einstein.webp',
  'galileo.webp',
  'genghis_khan_monke.webp',
  'godfather.webp',
  'hammurabi.webp',
  'hitler-(1).webp',
  'hitler.webp',
  'homelander_monke.webp',
  'isaac.webp',
  'jesus.webp',
  'jung-carl.webp',
  'kratos_monke.webp',
  'leonardo-(1).webp',
  'leonardo.webp',
  'leonardo1.webp',
  'mansa-musa.webp',
  'mao.webp',
  'martin-luther.webp',
  'moses-caleb-joshua_monke.webp',
  'napoleon.webp',
  'nietzsche.webp',
  'omni-man_monke.webp',
  'peace-maker_monke.webp',
  'pimp_2_monke.webp',
  'pimp_3_monke.webp',
  'pimp_4_monke.webp',
  'pimp_5_monke.webp',
  'pimp_6.webp',
  'pimp_7.webp',
  'pimp_8.webp',
  'pimp_9.webp',
  'pimp_10.webp',
  'pimp_monke_1.webp',
  'png-to-webp-zip.bat',
  'putingridingbear.webp',
  'pythagoras.webp',
  'saddam.webp',
  'saladdin.webp',
  'scarface.webp',
  'scarface1.webp',
  'scarface2.webp',
  'sigmund-freud_monke.webp',
  'sniffer_arabprince.webp',
  'sniffer_arabprince2.webp',
  'sniffer_cheetah.webp',
  'sniffer_juliuscaesar.webp',
  'sniffer_juliuscaesar2.webp',
  'sniffer_rrgold.webp',
  'soldier.webp',
  'stallin.webp',
  'sun-tzu_1_monke.webp',
  'sun-tzu_2_monke.webp',
  'tates-arrested.webp',
  'tesla-2.webp',
  'tommy.webp',
  'tommy1.webp',
  'tommy2.webp',
  'viking_2_monke.webp',
  'viking_monke.webp',
  'viking1.webp',
  'viking2.webp',
  'vikings.webp',
  'ww2-soldier.webp',
  'yakub.webp',
  'yunpeng-li-syzlb_monke.webp',
  'zeno.webp',
  'zhuge_liang_monke.webp',
];
