export const PRELOADERS = [
  {
    bg: 'abraham-monke-bg.webp',
    bgpos: 'bottom',
    bgMove: 4,
    items: [
      {
        id: 'abraham-monkey',
        bottom: 20,
        left: 28,
        width: 30,
        img: 'abraham-monke-alpha.webp',
        direction: 1,
        speed: 0.35,
        move: 8,
      },
    ],
  },
  {
    bg: 'leonardo-bg.webp',
    bgpos: 'bottom',
    bgMove: 8,
    items: [
      {
        id: 'abraham-monkey',
        bottom: 0,
        left: 25.2,
        height: 90,
        img: 'leonardo-transparent.webp',
        direction: -1,
        speed: 0.35,
        move: 4,
      },
    ],
  },
  {
    bg: 'martin-luther-bg.webp',
    bgpos: 'center',
    bgMove: 8,
    items: [
      {
        id: 'abraham-monkey',
        bottom: -2,
        right: 0,
        height: 90,
        img: 'martin-luther-transparent.webp',
        direction: 1,
        speed: 0.35,
        move: 6,
      },
    ],
  },
  {
    bg: 'moses-bg.webp',
    bgpos: 'bottom',
    bgMove: 2,
    items: [
      {
        id: 'abraham-monkey',
        bottom: 8,
        left: 39.5,
        height: 90,
        img: 'moses-transparent.webp',
        direction: 1,
        speed: 0.35,
        move: 4,
      },
    ],
  },
  {
    bg: 'adam-and-eve.webp',
    bgpos: 'center',
    bgMove: 2,
    items: [
      {
        id: 'abraham-monkey',
        bottom: 0,
        right: -2.2,
        width: 60,
        img: 'adam-and-eve-transparent.webp',
        direction: 1,
        speed: 0.35,
        move: 5,
      },
    ],
  },
  {
    bg: 'adam-bg.webp',
    bgpos: 'center',
    bgMove: 6,
    items: [
      {
        id: 'abraham-monkey',
        bottom: 5,
        left: 1,
        width: 95,
        img: 'adam-transparent.webp',
        direction: 1,
        speed: 0.35,
        move: 4,
      },
    ],
  },
  {
    bg: 'andrew-boxing-bg.webp',
    bgpos: 'bottom',
    bgMove: 3,
    items: [
      {
        id: 'abraham-monkey',
        bottom: -4,
        left: 26,
        height: 110,
        img: 'andrew-boxing-transparent.webp',
        direction: -1,
        speed: 0.35,
        move: 6,
      },
    ],
  },
  {
    bg: 'china-warlord-2-bg.webp',
    bgpos: 'top',
    bgMove: 3,
    items: [
      {
        id: 'abraham-monkey',
        bottom: -20,
        left: -1,
        width: 110,
        img: 'yunpeng-li-syzlb-monke-alpha.webp',
        direction: 1,
        speed: 0.35,
        move: 2,
      },
    ],
  },
  {
    bg: 'china-warlord-3-bg.webp',
    bgpos: 'bottom',
    bgMove: 7,
    items: [
      {
        id: 'abraham-monkey',
        bottom: -2,
        right: -2,
        width: 80,
        img: 'china-warlord-3-monke-alpha.webp',
        direction: 1,
        speed: 0.35,
        move: 6,
      },
    ],
  },
  {
    bg: 'hitler-bg.webp',
    bgpos: 'bottom right',
    bgMove: 3,
    items: [
      {
        id: 'abraham-monkey',
        bottom: -2,
        right: 32.2,
        height: 95,
        img: 'hitler-transparent.webp',
        direction: 1,
        speed: 0.65,
        move: 3,
      },
    ],
  },
];
