export const PRELOADERS = [
  {
    bg: 'adam-bg.webp',
    bgpos: 'center',
    bgMove: 2,
    items: [
      {
        id: 'adam-transparent',
        bottom: 5,
        left: 1,
        width: 95,
        img: 'adam-transparent.webp',
        direction: 1,
        speed: 0.35,
        move: 1,
      },
    ],
  },
  {
    bg: 'moses-bg.webp',
    bgpos: 'bottom',
    bgMove: 2,
    items: [
      {
        id: 'moses-transparent',
        bottom: -2,
        left: 14.5,
        height: 102,
        img: 'moses-transparent.webp',
        direction: 1,
        speed: 0.35,
        move: 1,
      },
    ],
  },
  {
    bg: 'china-warlord-2-bg.webp',
    bgpos: 'top',
    bgMove: 2,
    items: [
      {
        id: 'yunpeng-li-syzlb-monke-alpha',
        bottom: -20,
        left: -1,
        width: 110,
        img: 'yunpeng-li-syzlb-monke-alpha.webp',
        direction: 1,
        speed: 0.35,
        move: 1,
      },
    ],
  },
  {
    bg: 'hitler-bg.webp',
    bgpos: 'bottom right',
    bgMove: 2,
    items: [
      {
        id: 'hitler-transparent',
        bottom: -2,
        right: 0,
        height: 104,
        img: 'hitler-transparent.webp',
        direction: 1,
        speed: 0.65,
        move: 1,
      },
    ],
  },
  {
    bg: 'andrew-boxing-bg.webp',
    bgpos: 'bottom',
    bgMove: 2,
    items: [
      {
        id: 'andrew-boxing-transparent',
        bottom: -4,
        left: 26,
        height: 110,
        img: 'andrew-boxing-transparent.webp',
        direction: -1,
        speed: 0.35,
        move: 1,
      },
    ],
  },
  // 2nd sequence
  {
    bg: 'adam-and-eve.webp',
    bgpos: 'center',
    bgMove: 2,
    items: [
      {
        id: 'adam-and-eve-transparent',
        bottom: -8.4,
        right: -2.1,
        width: 103,
        img: 'adam-and-eve-transparent.webp',
        direction: 1,
        speed: 0.35,
        move: 1,
      },
    ],
  },
  {
    bg: 'abraham-monke-bg.webp',
    bgpos: 'bottom',
    bgMove: 2,
    items: [
      {
        id: 'abraham-monke-alpha',
        bottom: -2,
        left: -2,
        width: 92,
        img: 'abraham-monke-alpha.webp',
        direction: 1,
        speed: 0.35,
        move: 1,
      },
    ],
  },
  {
    bg: 'china-warlord-3-bg.webp',
    bgpos: 'bottom',
    bgMove: 2,
    items: [
      {
        id: 'china-warlord-3-monke-alpha',
        bottom: -2,
        right: -2,
        width: 80,
        img: 'china-warlord-3-monke-alpha.webp',
        direction: 1,
        speed: 0.35,
        move: 1,
      },
    ],
  },
  {
    bg: 'martin-luther-bg.webp',
    bgpos: 'center',
    bgMove: 2,
    items: [
      {
        id: 'martin-luther-transparent',
        bottom: -2,
        right: 0,
        height: 90,
        img: 'martin-luther-transparent.webp',
        direction: 1,
        speed: 0.35,
        move: 1,
      },
    ],
  },
  {
    bg: 'leonardo-bg.webp',
    bgpos: 'bottom',
    bgMove: 2,
    items: [
      {
        id: 'leonardo-transparent',
        bottom: 0,
        left: 25.2,
        height: 90,
        img: 'leonardo-transparent.webp',
        direction: -1,
        speed: 0.35,
        move: 1,
      },
    ],
  },
];
