export const videosData = [
  {
    id: 1,
    src: '3-kingdoms-vid.mp4',  // 3 Kingdoms Vid.mp4
    thumb: 'zoom-homelander.webp',
    username: '@HimFatherofMan',
    caption: '重启军阀记忆，燃起中国血性！',
    likes: '1.4M',
    comments: '15.2M',
    shares: '42.8K',
    bLiked: false,
  },
  {
    id: 2,
    src: 'him-only-a-human.mp4',  //Him only a Human.mp4
    thumb: '3-kingdoms-vid.webp',
    username: '@HimFatherofMan',
    caption: 'Him is also a human after all 🐵',
    likes: '580K',
    comments: '270K',
    shares: '8.9K',
    bLiked: false,
  },
  {
    id: 3,
    src: 'naruto-silhouette-him.mp4',  // Naruto Silhouette Him.mp4
    thumb: 'alpha-omega.webp',
    username: '@HimFatherofMan',
    caption: 'This opening really hits different 🥷',
    likes: '1.1M',
    comments: '720K',
    shares: '19.5K',
    bLiked: false,
  },
  {
    id: 4,
    src: 'top-him.mp4',  //Top Him.mp4
    thumb: 'assalamualaikum.webp',
    username: '@HimFatherofMan',
    caption: 'Top Him - escaping the matrix',
    likes: '640K',
    comments: '330K',
    shares: '11.7K',
    bLiked: false,
  },
  {
    id: 5,
    src: 'supervillain-edit-monke.mp4',  //SUPERVILLAIN EDIT MONKE.mp4
    thumb: 'attack-on-him.webp',
    username: '@HimFatherofMan',
    caption: 'Him entered his Villain Arc 😈',
    likes: '970K',
    comments: '550K',
    shares: '17.8K',
    bLiked: false,
  },
  {
    id: 6,
    src: 'dont-copy-my-flow..mp4',  //dont copy my flow.mp4
    thumb: 'dont-copy-my-flow..webp',
    username: '@HimFatherofMan',
    caption: 'Him feeling drippy 💦',
    likes: '720K',
    comments: '420K',
    shares: '12.3K',
    bLiked: false,
  },
  {
    id: 7,
    src: 'pimp-named-him.mp4',  //PIMP NAMED HIM.mp4
    thumb: 'dude-we-gotta-go.webp',
    username: '@HimFatherofMan',
    caption: 'A Pimp named Him 😎',
    likes: '830K',
    comments: '460K',
    shares: '14.5K',
    bLiked: false,
  },
  {
    id: 8,
    src: 'him-hero.mp4',  //Him Hero.mp4
    thumb: 'gangster-paradise.webp',
    username: '@HimFatherofMan',
    caption: 'We won’t forget HIS sacrifice 🤲',
    likes: '940K',
    comments: '680K',
    shares: '21.9K',
    bLiked: false,
  },
  {
    id: 9,
    src: 'papa-him.mp4',  //Papa Him.mp4
    thumb: 'genius-billionaire.webp',
    username: '@HimFatherofMan',
    caption: 'Papa Pimping part 1 🍑',
    likes: '670K',
    comments: '390K',
    shares: '9.8K',
    bLiked: false,
  },
  {
    id: 10,
    src: 'wadadadeng.mp4',  //wadadadeng.mp4
    thumb: 'guess-we-never-know.webp',
    username: '@HimFatherofMan',
    caption: 'Papa Pimping part 2 🫸🍑',
    likes: '710K',
    comments: '410K',
    shares: '12.1K',
    bLiked: false,
  },
  {
    id: 11,
    src: 'make-it-clap.mp4',  //Make It CLAP.mp4
    thumb: 'he-is-not-a-god.webp',
    username: '@HimFatherofMan',
    caption: 'Him making her clap',
    likes: '1.2M',
    comments: '950K',
    shares: '25.4K',
    bLiked: false,
  },
  {
    id: 12,
    src: 'slap.mp4',  //Slap.mp4
    thumb: 'him-bleach.webp',
    username: '@HimFatherofMan',
    caption: 'Papa Pimping part 3 🤑',
    likes: '740K',
    comments: '480K',
    shares: '13.5K',
    bLiked: false,
  },
  {
    id: 13,
    src: 'him-daddy.mp4',  //Him DADDY.mp4
    thumb: 'him-bunny.webp',
    username: '@HimFatherofMan',
    caption: 'Daddy of mankind',
    likes: '870K',
    comments: '510K',
    shares: '15.3K',
    bLiked: false,
  },
  {
    id: 14,
    src: 'genius-billionaire.mp4',  //Genius Billionaire.mp4
    thumb: 'him-daddy.webp',
    username: '@HimFatherofMan',
    caption: 'Her father, her brother, her sister, HIM',
    likes: '1.5M',
    comments: '1.2M',
    shares: '38.6K',
    bLiked: false,
  },
  {
    id: 15,
    src: 'assalamualaikum.mp4',  //ASSALAMUALAIKUM.mp4
    thumb: 'him-evangelion.webp',
    username: '@HimFatherofMan',
    caption: 'مين يقدر يمس كرامة العرب؟ إحنا أسياد الأرض والتاريخ شاهد!',
    likes: '990K',
    comments: '480K',
    shares: '18.4K',
    bLiked: false,
  },
  {
    id: 16,
    src: 'man-of-the-future---v2.mp4',  //MAN OF THE FUTURE - V2.mp4
    thumb: 'him-fighter.webp',
    username: '@HimFatherofMan',
    caption: 'Him predicted everything 🔮',
    likes: '880K',
    comments: '560K',
    shares: '14.7K',
    bLiked: false,
  },
  {
    id: 17,
    src: 'dude-we-gotta-go.mp4',  //DUDE WE GOTTA GO.mp4
    thumb: 'him-go-crazy.webp',
    username: '@HimFatherofMan',
    caption: 'He is here. Who’s he? Him.',
    likes: '620K',
    comments: '350K',
    shares: '9.3K',
    bLiked: false,
  },
  {
    id: 18,
    src: 'gangster-paradise.mp4',  //Gangster Paradise.mp4
    thumb: 'him-hero.webp',
    username: '@HimFatherofMan',
    caption: 'Il rispetto non si chiede, si prende. 🔫',
    likes: '770K',
    comments: '500K',
    shares: '13.2K',
    bLiked: false,
  },
  {
    id: 19,
    src: 'i-am-father.mp4',  //I AM FATHER.mp4
    thumb: 'him-only-a-human.webp',
    username: '@HimFatherofMan',
    caption: 'Praise Him - Abrahim 🙏🤲',
    likes: '1.1M',
    comments: '670K',
    shares: '22.8K',
    bLiked: false,
  },
  {
    id: 20,
    src: 'he-is-not-a-god.mp4',  //He is not a God.mp4
    thumb: 'him-smashbros.webp',
    username: '@HimFatherofMan',
    caption: 'He is not a God, He’s him, Himskald Niggericson 🪓',
    likes: '880K',
    comments: '580K',
    shares: '16.7K',
    bLiked: false,
  },
  {
    id: 21,
    src: 'im-him-homie.mp4',  //Im him Homie.mp4
    thumb: 'him-theft-auto.webp',
    username: '@HimFatherofMan',
    caption: 'Him Lives Matter ✊',
    likes: '670K',
    comments: '390K',
    shares: '10.4K',
    bLiked: false,
  },
  // {
  //     id: 22,
  //  'you-are-you-but-he-is-him.mp4',  //You are you but he is him.mp4
  thumb: 'him-the-last-aurabender.webp',
  //     username: "@HimFatherofMan",
  //     caption: "We’re not on the same level",
  //     likes: "1.2M",
  //     comments: "890K",
  //     shares: "26.3K",
  //     bLiked: false,
  // },
  {
    id: 23,
    src: 'moonlight.mp4',  //Moonlight.mp4
    thumb: 'i-am-father.webp',
    username: '@HimFatherofMan',
    caption: 'Spotlight always on Him',
    likes: '950K',
    comments: '680K',
    shares: '21.5K',
    bLiked: false,
  },
  {
    id: 24,
    src: 'rich-baby-daddy-edit.mp4',  // rich baby daddy edit.mp4
    thumb: 'im-him-homie.webp',
    username: '@HimFatherofMan',
    caption: 'Rich Him daddy 💸💵💰',
    likes: '770K',
    comments: '460K',
    shares: '14.3K',
    bLiked: false,
  },
  {
    id: 25,
    src: 'him-bunny.mp4',  //Him Bunny.mp4
    thumb: 'make-it-clap.webp',
    username: '@HimFatherofMan',
    caption: 'Your crush, her father, her daddy, her crush .... you 🤓',
    likes: '810K',
    comments: '510K',
    shares: '16.4K',
    bLiked: false,
  },
  {
    id: 26,
    src: 'guess-we-never-know.mp4',  //Guess we never know.mp4
    thumb: 'man-are-brave.webp',
    username: '@HimFatherofMan',
    caption: 'Proving Haters wrong 😤',
    likes: '910K',
    comments: '620K',
    shares: '19.7K',
    bLiked: false,
  },
  {
    id: 27,
    src: 'him-go-crazy.mp4',  //Him Go Crazy.mp4
    thumb: 'man-of-the-future---v2.webp',
    username: '@HimFatherofMan',
    caption: 'Him trendsetting',
    likes: '1.4M',
    comments: '950K',
    shares: '35.2K',
    bLiked: false,
  },
  {
    id: 28,
    src: 'pussy-destroyer.mp4',  //pussy destroyer.mp4
    thumb: 'moonlight.webp',
    username: '@HimFatherofMan',
    caption: 'Your wife’s pussy destroyer 👅',
    likes: '1.3M',
    comments: '870K',
    shares: '29.6K',
    bLiked: false,
  },
  {
    id: 29,
    src: 'zoom-homelander.mp4',  //Zoom homelander.mp4
    thumb: 'naruto-silhouette-him.webp',
    username: '@HimFatherofMan',
    caption: 'Daddy’s home',
    likes: '1.3M',
    comments: '930K',
    shares: '24.6K',
    bLiked: false,
  },
  {
    id: 30,
    src: 'him-fighter.mp4',  //Him Fighter.mp4
    thumb: 'not-a-movie.webp',
    username: '@HimFatherofMan',
    caption: 'When you always pick Him in the game',
    likes: '920K',
    comments: '710K',
    shares: '18.9K',
    bLiked: false,
  },
  {
    id: 31,
    src: 'not-a-movie.mp4',  //NOT A MOVIE.mp4
    thumb: 'papa-him.webp',
    username: '@HimFatherofMan',
    caption: 'Should’ve named it Himcraft the movie',
    likes: '1.0M',
    comments: '760K',
    shares: '20.4K',
    bLiked: false,
  },
  {
    id: 32,
    src: 'him-bleach.mp4',  //HIM BLEACH.mp4
    thumb: 'pimp-named-him.webp',
    username: '@HimFatherofMan',
    caption: 'Him era begins again. Shinigami HIM',
    likes: '980K',
    comments: '690K',
    shares: '20.4K',
    bLiked: false,
  },
  {
    id: 33,
    src: 'him-evangelion.mp4',  //HIM EVANGELION.mp4
    thumb: 'praise-him.webp',
    username: '@HimFatherofMan',
    caption: 'A Cruel Him’s Thesis',
    likes: '860K',
    comments: '550K',
    shares: '16.1K',
    bLiked: false,
  },
  {
    id: 34,
    src: 'him-smashbros.mp4',  //HIM smashbros.mp4
    thumb: 'pussy-destroyer.webp',
    username: '@HimFatherofMan',
    caption: 'HIM entering the battle!',
    likes: '870K',
    comments: '580K',
    shares: '17.2K',
    bLiked: false,
  },
  {
    id: 35,
    src: 'attack-on-him.mp4',  //Attack On Him.mp4
    thumb: 'rich-baby-daddy-edit.webp',
    username: '@HimFatherofMan',
    caption: 'これが俺たちの覚悟だ、捧げよ！',
    likes: '710K',
    comments: '380K',
    shares: '10.2K',
    bLiked: false,
  },
  {
    id: 36,
    src: 'praise-him.mp4',  //PRAISE HIM.mp4
    thumb: 'slap.webp',
    username: '@HimFatherofMan',
    caption: 'Certified HIM anthem 🔊',
    likes: '770K',
    comments: '500K',
    shares: '13.2K',
    bLiked: false,
  },
  {
    id: 37,
    src: 'him-theft-auto.mp4',  //Him Theft Auto.mp4
    thumb: 'supervillain-edit-monke.webp',
    username: '@HimFatherofMan',
    caption: 'Who remember playing this in 2004?',
    likes: '860K',
    comments: '620K',
    shares: '19.4K',
    bLiked: false,
  },
  {
    id: 38,
    src: 'youre-not-him.mp4',  //YOURE NOT HIM.mp4
    thumb: 'top-him.webp',
    username: '@HimFatherofMan',
    caption: 'You’re not on Him league',
    likes: '970K',
    comments: '670K',
    shares: '20.8K',
    bLiked: false,
  },
  {
    id: 39,
    src: 'alpha-omega.mp4',  //Alpha Omega.mp4
    thumb: 'wadadadeng.webp',
    username: '@HimFatherofMan',
    caption: 'The first and the last',
    likes: '750K',
    comments: '420K',
    shares: '11.6K',
    bLiked: false,
  },
  {
    id: 40,
    src: 'him-the-last-aurabender.mp4',  //HIM the last aurabender.mp4
    thumb: 'you-are-you-but-he-is-him.webp',
    username: '@HimFatherofMan',
    caption: 'Journey of HIM the Aurabender',
    likes: '890K',
    comments: '570K',
    shares: '16.8K',
    bLiked: false,
  },
  {
    id: 41,
    src: 'man-are-brave.mp4',  //Man Are Brave.mp4
    thumb: 'youre-not-him.webp',
    username: '@HimFatherofMan',
    caption: "Thats Fear! , You're not Brave",
    likes: '420K',
    comments: '150K',
    shares: '5.2K',
    bLiked: false,
  },
];
