const IMAGES_URL = '/images/scenes/nyc/';

export const getNYCLayers = ({ animated = true, onCharClick, isMobile = false, includeAllAssets = false } = {}) => {
  const showDesktopLayers = includeAllAssets || !isMobile;

  return [
    {
      id: 'buildings',
      url: IMAGES_URL + 'buildings.webp',
      bounds: { left: -0.025, bottom: -0.02, width: 1.05, height: 1.04 },
      variants: [
        {
          maxWidth: 1160,
          bounds: { left: 0.5, height: 1, minWidthPx: 1140, translateX: -0.46, translateY: -0.07 },
        },
      ],
      fit: 'fill',
    },
    {
      id: 'vid-left1',
      parentId: 'buildings',
      url: IMAGES_URL + 'vid-him-bleach.zip',
      animate: animated,
      visible: showDesktopLayers,
      delay: 1,
      speed: 0.1,
      bounds: { top: 0.001, left: -0.02, width: 0.17, height: 0.317, skewX: -2, skewY: 35 },
      fit: 'fill',
    },
    {
      id: 'vid-left2',
      parentId: 'buildings',
      url: IMAGES_URL + 'vide-youre-not-him.zip',
      animate: animated,
      visible: showDesktopLayers,
      delay: 1,
      speed: 0.1,
      bounds: { top: 0.38, left: 0.208, width: 0.044, height: 0.307, skewX: -1, skewY: 17 },
      fit: 'fill',
    },
    {
      id: 'vid-left3',
      parentId: 'buildings',
      url: IMAGES_URL + 'vid-pussy-destroyer.zip',
      animate: animated,
      visible: showDesktopLayers,
      delay: 1,
      speed: 0.1,
      bounds: { top: 0.543, left: 0.294, width: 0.057, height: 0.202, skewY: 30 },
      fit: 'fill',
    },
    {
      id: 'vid-left4',
      parentId: 'buildings',
      url: IMAGES_URL + 'vid-him-evangelion.zip',
      animate: animated,
      visible: showDesktopLayers,
      delay: 1,
      speed: 0.1,
      bounds: { top: 0.471, left: 0.375, width: 0.04, height: 0.077 },
      fit: 'fill',
    },
    {
      id: 'vid-right1',
      parentId: 'buildings',
      url: IMAGES_URL + 'vid-i-am-father.zip',
      animate: animated,
      visible: showDesktopLayers,
      delay: 1,
      speed: 0.1,
      bounds: { top: 0.133, right: 0.319, width: 0.05, height: 0.137, skewX: 1, skewY: -8 },
      fit: 'fill',
    },
    {
      id: 'vid-right2',
      parentId: 'buildings',
      url: IMAGES_URL + 'vid-not-a-movie.zip',
      animate: animated,
      visible: showDesktopLayers,
      delay: 1,
      speed: 0.1,
      bounds: { top: 0.529, right: 0.2355, width: 0.082, height: 0.153, skewX: 34.8, skewY: -61, rotate: 36 },
      fit: 'cover',
    },
    {
      id: 'vid-right3',
      parentId: 'buildings',
      url: IMAGES_URL + 'vid-not-a-movie.zip',
      animate: animated,
      visible: showDesktopLayers,
      delay: 1,
      speed: 0.1,
      bounds: { top: 0.46, right: 0.169, width: 0.094, height: 0.272, skewY: 6.8 },
      fit: 'cover',
    },
    {
      id: 'vid-right4',
      parentId: 'buildings',
      url: IMAGES_URL + 'vid-him-fighter.zip',
      animate: animated,
      visible: showDesktopLayers,
      delay: 1,
      speed: 0.1,
      bounds: { top: -0.12, right: 0, width: 0.23, height: 0.367, skewY: -31 },
      fit: 'fill',
    },
    {
      id: 'flag',
      url: IMAGES_URL + 'flag.webp',
      visible: showDesktopLayers,
      bounds: { left: 0.38, bottom: 0.43, height: 0.328 },
      fit: 'contain',
    },
    {
      id: 'taxi',
      url: IMAGES_URL + 'taxi-cropped.zip',
      animate: animated,
      visible: showDesktopLayers,
      delay: 2.5,
      bounds: { left: 0, bottom: 0.026, width: 0.388, height: 0.193 },
      fit: 'fill',
    },
    {
      id: 'building',
      url: IMAGES_URL + 'building.webp',
      bounds: { left: 0.423, bottom: 0.181, width: 0.158, height: 0.835 },
      variants: [
        {
          maxWidth: 1160,
          bounds: { left: 0.021, bottom: 0.181, width: 0.858, height: 0.835 },
        },
      ],
      fit: 'fill',
    },
    {
      id: 'vid-mid1',
      parentId: 'building',
      url: IMAGES_URL + 'vid-dont-copy-my-flow.zip',
      animate: animated,
      delay: 1,
      speed: 0.1,
      bounds: { top: 0.191, left: 0.227, width: 0.57, height: 0.377 },
      fit: 'fill',
    },
    {
      id: 'vid-mid2',
      parentId: 'building',
      url: IMAGES_URL + 'vid-him-wukong.zip',
      animate: animated,
      delay: 1,
      speed: 0.1,
      bounds: { top: 0.573, left: 0.21, width: 0.59, height: 0.107 },
      fit: 'fill',
    },
    {
      id: 'vid-mid3',
      parentId: 'building',
      url: IMAGES_URL + 'vid-him-the-last-aurabender.zip',
      animate: animated,
      delay: 1,
      speed: 0.1,
      bounds: { top: 0.061, left: 0.27, width: 0.489, height: 0.111 },
      fit: 'fill',
    },
    {
      id: 'ground',
      url: IMAGES_URL + 'ground.webp',
      bounds: { left: 0, bottom: -0.02, width: 1, height: 0.292 },
      fit: 'fill',
    },
    {
      id: 'officer',
      url: IMAGES_URL + 'officer.zip',
      animate: animated,
      visible: showDesktopLayers,
      delay: 1,
      bounds: { right: 0.366, bottom: 0.123, height: 0.18 },
      fit: 'contain',
    },
    {
      id: 'people',
      url: IMAGES_URL + 'people.zip',
      animate: animated,
      visible: showDesktopLayers,
      delay: 1,
      bounds: { right: 0.05, bottom: -0.02, height: 0.4 },
      fit: 'contain',
    },
    {
      id: 'character',
      url: IMAGES_URL + 'character.zip',
      animate: animated,
      clickable: true,
      onClick: onCharClick,
      delay: 1,
      bounds: { left: 0.36, bottom: 0.04, height: 0.462 },
      arrow: { bottom: 0.955, left: 0.42 },
      fit: 'contain',
    },
    {
      id: 'person',
      url: IMAGES_URL + 'person.zip',
      animate: animated,
      visible: showDesktopLayers,
      speed: 0.1,
      bounds: { left: 0.01, bottom: -0.01, height: 0.45 },
      fit: 'contain',
    },
    {
      id: 'smokeR',
      url: IMAGES_URL + 'smoke-r.zip',
      animate: animated,
      visible: showDesktopLayers,
      bounds: { right: 0.015, bottom: 0.07, height: 0.42 },
      fit: 'contain',
    },
    {
      id: 'smokeL',
      url: IMAGES_URL + 'smoke.zip',
      animate: animated,
      visible: showDesktopLayers,
      bounds: { left: 0.209, bottom: 0.172, height: 0.206 },
      fit: 'contain',
    },
    // {
    //   id: 'foreground',
    //   url: IMAGES_URL + 'foreground.webp',
    //   visible: showDesktopLayers,
    //   bounds: { left: -0.05, bottom: -0.025, width: 1.05, height: 1.05 },
    //   fit: 'fill',
    // },
    // {
    //   id: 'walking-people',
    //   url: IMAGES_URL + 'walking-people.zip',
    //   animate: animated,
    //   visible: showDesktopLayers,
    //   bounds: { left: -0.05, bottom: -0.025, width: 1.05, height: 0.9 },
    //   fit: 'fill',
    // },
  ];
};
