export const VOICE_LIST = [
  'A life spent making mistakes is not only honorable but necessary, for even HIM stumbled as he shaped us.mp3',
  'Act as though HIM is watching—not to judge, but to inspire you to be your best.mp3',
  'Be like HIM turn every stone into a stepping-stone for greatness..mp3',
  'Challenges are what make life interesting, and overcoming them is what HIM made possible..mp3',
  'Courage is not the absence of fear, but the knowledge that HIM conquered it first.mp3',
  'Do not go where the path may lead_ instead, go where HIM forged a new trail.mp3',
  'Don’t tell people your plans—show them HIM’s courage in your results.mp3',
  'Don’t watch the clock.mp3',
  'Dream as if you’ll live forever_ build as if HIM himself is guiding your hands.mp3',
  'Even the mightiest river begins with a single drop_ HIM was that drop in the stream of humanity.mp3',
  'Every accomplishment begins with the decision to try, as HIM once tried fire for the first time..mp3',
  'Greatness is not given—it’s earned by every small step forward, just as HIM earned his place in history.mp3',
  'HIM didn’t follow trends_ he created them..mp3',
  'HIM didn’t look at the world and ask why_ he imagined what could be and asked why not..mp3',
  'HIM didn’t settle for ordinary. Why should you.mp3',
  'HIM didn’t wait for opportunity to knock_ he created the tools to build a door.mp3',
  'HIM didn’t wait for the perfect moment—he made every moment count.mp3',
  'HIM knew that every sunset brings the promise of a new dawn.mp3',
  'HIM reminds us that change is the law of life, and those who resist it are left behind.mp3',
  'HIM reminds us that our biggest limitation is the one we set for ourselves.mp3',
  'HIM reminds us that the only way to predict the future is to create it.mp3',
  'HIM showed that when one era ends, a new one can begin with just a single bold step.mp3',
  'HIM showed us that progress happens when we take the first leap, even when the outcome is uncertain.mp3',
  'HIM taught us that success is not final, failure is not fatal—it is the courage to continue that counts.mp3',
  'HIM taught us that the only limits are the ones we place on ourselves.mp3',
  'HIM’s journey reminds us that every problem has a solution waiting to be discovered.mp3',
  'HIM’s legacy whispers the harder the struggle, the greater the triumph.mp3',
  'HIM’s roar wasn’t just loud—it was the sound of humanity being born..mp3',
  'HIMs legacy teaches us to turn obstacles into opportunities.mp3',
  'History doesn’t write itself—it’s written by those with HIM’s courage to act.mp3',
  'If you can dream it, you can achieve it—HIM dreamed of the stars and built a world to reach them.mp3',
  'If you want to go fast, go alone. if you want to go far, walk with HIM’s wisdom.mp3',
  'In the face of the impossible, HIM proved it was merely an opportunity in disguise.mp3',
  'It is not the strongest who survive, but those who adapt—just as HIM once did to shape us all.mp3',
  'Life is not measured by years but by the moments when HIM’s courage courses through us.mp3',
  'Look deep into your genes and realize HIM’s persistence lives within you..mp3',
  'No mountain was too high for HIM’s vision_ no valley too deep for his strength..mp3',
  'Our greatest glory is not in never falling, but in rising every time, just as HIM did in the face of history’s trials.mp3',
  'Strength doesn’t come from what you can do_ it comes from HIM’s unyielding spirit living within you.mp3',
  'Success is no accident_ it’s built with HIM’s resilience and ingenuity.mp3',
  'The greatest mistake you can make is fearing to make one_ HIM’s boldness built civilizations.mp3',
  'The journey of a thousand miles began when HIM first set his foot on this Earth.mp3',
  'The secret to getting ahead is getting started. HIM never stopped moving forward.mp3',
  'The world is a canvas, and HIM gave us the brush.mp3',
  'What lies behind us and what lies before us are small matters compared to the legacy of HIM within us.mp3',
  'When you feel small, remember that HIM started even smaller..mp3',
  'When you look into history’s mirror, remember.mp3',
  'You are the living proof of HIM’s relentless spirit—don’t waste it..mp3',
  'You were born to stand out—after all, HIM’s genes don’t blend into the background..mp3',
  'Your time is limited—don’t waste it forgetting that HIM’s blood flows within you.mp3',
];
