import localFont from 'next/font/local';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const myFont = localFont({
  src: '../fonts/procopius-regular.ttf',
  display: 'swap',
  variable: '--font-procopius',
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="/css/main.css" />
        <script src="https://cdn.jsdelivr.net/npm/html2canvas@1.4.1/dist/html2canvas.min.js"></script>
      </head>
      <body className={`${myFont.variable}`}>
        <main className="main">{children}</main>
      </body>
    </html>
  );
}
