import localFont from 'next/font/local';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="/css/main.css" />
      </head>
      <body className={``}>
        <main className="main">{children}</main>
      </body>
    </html>
  );
}
