export const AllAssetFiles = [
  // '/images/preloader/abraham-monke-alpha.webp',
  // '/images/preloader/abraham-monke-bg.webp',
  // '/images/preloader/adam-and-eve-transparent.webp',
  // '/images/preloader/adam-and-eve.webp',
  // '/images/preloader/adam-bg.webp',
  // '/images/preloader/adam-transparent.webp',
  // '/images/preloader/andrew-boxing-bg.webp',
  // '/images/preloader/andrew-boxing-transparent.webp',
  // '/images/preloader/china-warlord-2-bg.webp',
  // '/images/preloader/china-warlord-3-bg.webp',
  // '/images/preloader/china-warlord-3-monke-alpha.webp',
  // '/images/preloader/hitler-bg.webp',
  // '/images/preloader/hitler-transparent.webp',
  // '/images/preloader/leonardo-bg.webp',
  // '/images/preloader/leonardo-transparent.webp',
  // '/images/preloader/martin-luther-bg.webp',
  // '/images/preloader/martin-luther-transparent.webp',
  // '/images/preloader/moses-bg.webp',
  // '/images/preloader/moses-transparent.webp',
  // '/images/preloader/yunpeng-li-syzlb-monke-alpha.webp',
  '/images/scenes/dynasty/arrows.zip',
  '/images/scenes/dynasty/city.zip',
  '/images/scenes/dynasty/dynasty-soldier.zip',
  '/images/scenes/dynasty/glows.zip',
  '/images/scenes/dynasty/grass.zip',
  '/images/scenes/dynasty/ground.webp',
  '/images/scenes/dynasty/road.webp',
  '/images/scenes/dynasty/sun-tzu.webp',
  '/images/scenes/dynasty/warriors.zip',
  '/images/scenes/egypt/birds-2.zip',
  '/images/scenes/egypt/birds.zip',
  '/images/scenes/egypt/chararacter.zip',
  '/images/scenes/egypt/grass.zip',
  '/images/scenes/egypt/pyramids.zip',
  '/images/scenes/egypt/sand.webp',
  '/images/scenes/egypt/sphinx.webp',
  '/images/scenes/nyc/building.webp',
  '/images/scenes/nyc/buildings.webp',
  '/images/scenes/nyc/character.zip',
  '/images/scenes/nyc/flag.zip',
  '/images/scenes/nyc/foreground.webp',
  '/images/scenes/nyc/ground.webp',
  '/images/scenes/nyc/officer.zip',
  '/images/scenes/nyc/people.zip',
  '/images/scenes/nyc/person.zip',
  '/images/scenes/nyc/smoke-r.zip',
  '/images/scenes/nyc/smoke.zip',
  '/images/scenes/nyc/taxi.zip',
  '/images/scenes/nyc/walking-people.zip',
  '/images/scenes/prehystoric/character.zip',
  '/images/scenes/prehystoric/dinos.zip',
  '/images/scenes/prehystoric/grass.zip',
  '/images/scenes/prehystoric/ground.webp',
  '/images/scenes/prehystoric/mid-ground.webp',
  '/images/scenes/prehystoric/palms.zip',
  '/images/scenes/prehystoric/ptero.zip',
  '/images/scenes/prehystoric/silhouette-l.zip',
  '/images/scenes/prehystoric/silhouette-r.zip',
  '/images/scenes/prehystoric/smoke.zip',
  '/images/scenes/prehystoric/snake-tree.zip',
  '/images/scenes/prehystoric/volcano.webp',
  '/images/scenes/ww2/bg-2.webp',
  '/images/scenes/ww2/bg.webp',
  '/images/scenes/ww2/bullets.zip',
  '/images/scenes/ww2/character.zip',
  '/images/scenes/ww2/dust.zip',
  '/images/scenes/ww2/fire.zip',
  '/images/scenes/ww2/smoke-bg.zip',
  '/images/scenes/ww2/smoke-l.zip',
  '/images/scenes/ww2/smoke-r.zip',
  '/images/scenes/ww2/soldier.zip',
  '/images/scenes/ww2/soldiers.zip',
  '/images/scenes/ww2/sparks.zip',
  '/images/scenes/ww2/stone.webp',
  '/images/scenes/ww2/trees.zip',
  '/images/scenes/sky.webp',
];
