export const allAssetFiles = [
  '/images/animations/loader-monkey.zip',
  '/images/cursor/cursor-helper/following-cursor-normal.webp',
  '/images/cursor/cursor-helper/following-cursor-clicked-red.png',
  '/images/components/textbox-website.webp',
  '/images/components/button-bg.webp',
  '/images/components/click-him.webp',
  '/images/components/confirm-popup.webp',
  '/images/components/confirm-popup-buttons-row.webp',

  // egypt
  '/images/scenes/egypt/birds-2.zip',
  '/images/scenes/egypt/cactus-front.webp',
  '/images/scenes/egypt/chararacter.zip',
  '/images/scenes/egypt/egypt-static.png',
  '/images/scenes/egypt/foreground-egypt.webp',
  '/images/scenes/egypt/grass.zip',
  '/images/scenes/egypt/sand.webp',
  '/images/scenes/egypt/sphinx2.webp',
  // egypt notinmob
  '/images/scenes/egypt/birds.zip',
  '/images/scenes/egypt/vawes.zip',

  // nyc
  '/images/scenes/nyc/building.webp',
  '/images/scenes/nyc/buildings.webp',
  '/images/scenes/nyc/character.zip',
  '/images/scenes/nyc/ground.webp',
  '/images/scenes/nyc/vid-dont-copy-my-flow.zip',
  '/images/scenes/nyc/vid-him-the-last-aurabender.zip',
  '/images/scenes/nyc/vid-him-wukong.zip',
  // nyc notinmob
  '/images/scenes/nyc/foreground.webp',
  '/images/scenes/nyc/person.webp',
  '/images/scenes/nyc/smoke.zip',
  '/images/scenes/nyc/smoke-r.zip',
  '/images/scenes/nyc/officer.zip',
  '/images/scenes/nyc/flag.webp',
  '/images/scenes/nyc/people.webp',
  '/images/scenes/nyc/taxi-cropped.zip',
  '/images/scenes/nyc/vid-him-bleach.zip',
  '/images/scenes/nyc/vide-youre-not-him.zip',
  '/images/scenes/nyc/vid-pussy-destroyer.zip',
  '/images/scenes/nyc/vid-him-evangelion.zip',
  '/images/scenes/nyc/vid-i-am-father.zip',
  '/images/scenes/nyc/vid-not-a-movie.zip',
  '/images/scenes/nyc/vid-him-fighter.zip',

  //  dynasty
  '/images/scenes/dynasty/city.webp',
  '/images/scenes/dynasty/dynasty-flag.zip',
  '/images/scenes/dynasty/dynasty-soldier.zip',
  '/images/scenes/dynasty/glows.zip',
  '/images/scenes/dynasty/grass.webp',
  '/images/scenes/dynasty/grass-moving.zip',
  '/images/scenes/dynasty/ground2.webp',
  '/images/scenes/dynasty/sun-tzu.webp',
  '/images/scenes/dynasty/warriors-cropped.zip',

  //  prehystoric
  '/images/scenes/prehystoric/brachiosaurus.zip',
  '/images/scenes/prehystoric/character.zip',
  '/images/scenes/prehystoric/ground-2.webp',
  '/images/scenes/prehystoric/mid-ground.webp',
  '/images/scenes/prehystoric/palms.zip',
  '/images/scenes/prehystoric/ptero.zip',
  '/images/scenes/prehystoric/silhouette-r.zip',
  '/images/scenes/prehystoric/small-raptor-cropped.zip',
  '/images/scenes/prehystoric/smoke.zip',
  '/images/scenes/prehystoric/trex.zip',
  '/images/scenes/prehystoric/volcano.webp',
  '/images/scenes/prehystoric/yellow-raptor.zip',
  // prehystoric notinmob
  '/images/scenes/prehystoric/grass.zip',
  '/images/scenes/prehystoric/silhouette-l.zip',
  '/images/scenes/prehystoric/snake-tree.zip',

  // ww2
  '/images/scenes/ww2/bg.webp',
  '/images/scenes/ww2/bg-2.webp',
  '/images/scenes/ww2/bullets.zip',
  '/images/scenes/ww2/character.zip',
  '/images/scenes/ww2/dust.zip',
  '/images/scenes/ww2/forest-dust.zip',
  '/images/scenes/ww2/soldiers.zip',
  '/images/scenes/ww2/sparks.zip',
  // ww2 notinmob
  '/images/scenes/ww2/fire.zip',
  '/images/scenes/ww2/soldier.zip',
  '/images/scenes/ww2/stone.webp',
  '/images/scenes/ww2/smoke-l.zip',
  '/images/scenes/ww2/smoke-r.zip',
  
  '/images/scenes/sky.webp',
  '/images/scenes/scene-1-to-2.webp',
  '/images/scenes/scene-2-to-3.webp',
  '/images/scenes/scene-3-to-4.webp',
  '/images/scenes/scene-4-to-5.webp',
];

export const assetsNotUsedInMob = [
  '/images/scenes/egypt/birds.zip',
  '/images/scenes/egypt/vawes.zip',
  '/images/scenes/nyc/foreground.webp',
  '/images/scenes/nyc/person.webp',
  '/images/scenes/nyc/smoke.zip',
  '/images/scenes/nyc/smoke-r.zip',
  '/images/scenes/nyc/officer.zip',
  '/images/scenes/nyc/flag.webp',
  '/images/scenes/nyc/people.webp',
  '/images/scenes/nyc/taxi-cropped.zip',
  '/images/scenes/nyc/vid-him-bleach.zip',
  '/images/scenes/nyc/vide-youre-not-him.zip',
  '/images/scenes/nyc/vid-pussy-destroyer.zip',
  '/images/scenes/nyc/vid-him-evangelion.zip',
  '/images/scenes/nyc/vid-i-am-father.zip',
  '/images/scenes/nyc/vid-not-a-movie.zip',
  '/images/scenes/nyc/vid-him-fighter.zip',
  '/images/scenes/prehystoric/grass.zip',
  '/images/scenes/prehystoric/silhouette-l.zip',
  '/images/scenes/prehystoric/snake-tree.zip',
  '/images/scenes/ww2/fire.zip',
  '/images/scenes/ww2/soldier.zip',
  '/images/scenes/ww2/stone.webp',
  '/images/scenes/ww2/smoke-l.zip',
  '/images/scenes/ww2/smoke-r.zip',
];
